# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: unsatais
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: products-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: products-service

provider:
  name: aws
    runtime: python3.9
    region: us-east-1
    environment:
      DYNAMO_TABLE: Products
      AWS_REGION: ${env:AWS_REGION}
      
functions:
  createProduct:
    handler: handler.create_product
    events:
      - http:
          path: products
          method: post

  getAllProducts:
    handler: handler.get_all_products
    events:
      - http:
          path: products
          method: get

  getProduct:
    handler: handler.get_product
    events:
      - http:
          path: products/{product_id}
          method: get

  updateProduct:
    handler: handler.update_product
    events:
      - http:
          path: products/{product_id}
          method: put

  deleteProduct:
    handler: handler.delete_product
    events:
      - http:
          path: products/{product_id}
          method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        AttributeDefinitions:
          - AttributeName: ProductID
            AttributeType: S
        KeySchema:
          - AttributeName: ProductID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
